[buildPlans.iosevka-custom]
family = "Iosevka"          # <iosevka-custom> is your plan name
spacing = "fontconfig-mono" # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
serifs = "sans"             # Optional; Values: `sans` or `slab`
no-cv-ss = false

###################################################################################################
# Configure variants

# Optional; Whether to inherit a `ss##` variant
# [buildPlans.iosevka-custom.variants]
# inherits = "ss01"

# Optional; Configure single character's variant
[buildPlans.iosevka-custom.variants.design]
ampersand = "closed"
ascii-grave = "straight"
ascii-single-quote = "straight"
at = "threefold"
brace = "straight"
capital-g = "toothed-serifless-hooked"
capital-z = "straight-serifless"
cent = "through"
eszet = "sulzbacher-descending" # ß (beta symbol)
four = "closed"
lig-ltgteq = "flat"
number-sign = "upright"
paren = "large-contour"
percent = "rings-continuous-slash"
question = "smooth"
six = "closed-contour"
z = "straight-serifless"
zero = "slashed"

# End variant section
###################################################################################################

###################################################################################################
# Configure ligations

[buildPlans.iosevka-custom.ligations]
# Optional; inherits an existing ligation set
# inherits = "default-calt"

# Optional; disable specific ligation groups, overrides inherited ligation set
disables = []

# Optional; enable specific ligation groups, overrides inherited ligation set
enables  = [
    'arrow',
    'center-ops',
    'connected-number-sign',
    'connected-underscore',
    'dot-as-operator',
    'eqeq',
    'exeq',
    'html-comment',
    'ineq',
    'kern-dotty',
    'llgg',
    'llggeq',
    'ltgt-diamond',
    'trig',
]

# End ligation section
###################################################################################################


###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.

# [buildPlans.iosevka-custom.weights.regular]
# shape = 400  # Weight for glyph shapes.
# menu  = 400  # Weight for the font's names.
# css   = 400  # Weight for webfont CSS.

# [buildPlans.iosevka-custom.weights.book]
# shape = 450
# menu  = 450  # Use 450 here to name the font's weight "Book"
# css   = 450

# [buildPlans.iosevka-custom.weights.bold]
# shape = 700
# menu  = 700
# css   = 700

# End weight section
###################################################################################################

###################################################################################################
# Override default building slope sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slopes would be built.

# [buildPlans.iosevka-custom.slopes]
# upright = "normal"
# italic = "italic"
# oblique = "oblique"

# End slope section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#             while "menu" only supports integers between 1 and 9 (inclusive).
#             The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#             width are equal to, or a simple multiple of the unit width.
#             If you decide to use custom widths you have to define all the widths you plan to use,
#             otherwise they will not be built.

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.widths.normal]
shape = 600      # Unit Width, measured in 1/1000 em.
menu  = 5        # Width grade for the font's names.
css   = "normal" # "font-stretch' property of webfont CSS.

# [buildPlans.iosevka-custom.widths.extended]
# shape = 600
# menu  = 7
# css   = "expanded"

# End width section
###################################################################################################

###################################################################################################
# Character Exclusion
# Specify character ranges in the section below to exclude certain characters from the font being
# built.

[buildPlans.iosevka-custom.exclude-chars]
ranges = [
    [9829,   9829], # Octicons Part 1: 0x2665
    [9889,   9889], # Octicons Part 2: 0x26a1
    [62076, 62076], # Octicons Part 3: 0xf27c
    [62464, 62632], # Octicons Part 4: 0xf400 - 0xf4a8
    [61440, 62176], # Font Awesome: 0xf000-0xf2e0
    [57856, 58025], # Font Awesome Extension: 0xe200 - 0xe2a9
    [58874, 58923], # Seti-UI + Custom: 0xe5fa - 0xe62b
    [59136, 59333], # Devicons: 0xe700 - 0xe7c5
    [62208, 62227], # Font Logos: 0xf300 - 0xf313
]

# End character exclusion
###################################################################################################

###################################################################################################
# Compatibility Ligatures
# Certain applications like Emacs does not support proper programming liagtures provided by
# OpenType, but can support ligatures provided by PUA codepoints. Therefore you can edit the
# following section to build PUA characters that are generated from the OpenType ligatures.
# Remove this section when compatibility ligatures are not needed.

# [[buildPlans.iosevka-custom.compatibility-ligatures]]
# unicode = 57600 # 0xE100
# featureTag = 'calt'
# sequence = '<*>'

# End compatibility ligatures section
###################################################################################################

###################################################################################################
# Metric overrides
# Certain metrics like line height (leading) could be overridden in your build plan file.
# Edit the values to change the metrics. Remove this section when overriding is not needed.

# [buildPlans.iosevka-custom.metric-override]
# leading = 1250
# winMetricAscenderPad = 0
# winMetricDescenderPad = 0
# powerlineScaleY = 1
# powerlineScaleX = 1
# powerlineShiftY = 0
# powerlineShiftX = 0

# End metric override section
###################################################################################################
